#!/bin/bash

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root"
   exit 1
fi

echo "Remove ScreenRulerZoom"
for I in share/screenrulerzoom bin/screenrulerzoom share/applications/screenrulerzoom.desktop
do
  rm -r "/usr/$I"
done

echo
echo "Uninstallation Complete"
